### ISSUE TITLE
What is the args(0) doing here?

### ISSUE THREAD

**Issue by HaFred** [leros-dev/leros#6]
I know most of the issues are raising a long time ago, but it seems the repo is still updating, I would like to know what is this args(0) actually meaning here? The chiselTester failed and the sbt shows that `not found: value args`
https://github.com/leros-dev/leros/blob/2cde258623e90b82ebbd4f1052b7c79227e583b2/src/test/scala/leros/LerosTester.scala#L35

**Comment by schoeberl** [comment]
Args(0) contains the application. Look into the Makefile how to run an example.

Yes, Leros is still a not active work-in-progress. Hope to finish it during this summer.

**Comment by HaFred** [comment]
I followed the makefile and to run the lerostester but it seems failed... Would you please give me some suggestions? @schoeberl  Thank you very much!
```
                                             ^
[IJ]sbt:leros> test:runMain leros.LerosTester asm/base.s
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] running leros.LerosTester asm/base.s
Testing Leros
[info] [0.003] Elaborating design...
[error] (run-main-0) chisel3.internal.ChiselException: Exception thrown when elaborating ChiselGeneratorAnnotation
[error] chisel3.internal.ChiselException: Exception thrown when elaborating ChiselGeneratorAnnotation
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:55)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:19)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:18)
[error] 	at chisel3.iotesters.setupTreadleBackend$.apply(TreadleBackend.scala:143)
[error] 	at chisel3.iotesters.Driver$.$anonfun$execute$2(Driver.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[error] 	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at logger.Logger$.makeScope(Logger.scala:166)
[error] 	at logger.Logger$.makeScope(Logger.scala:127)
[error] 	at chisel3.iotesters.Driver$.$anonfun$execute$1(Driver.scala:38)
[error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.iotesters.Driver$.execute(Driver.scala:38)
[error] 	at chisel3.iotesters.Driver$.execute(Driver.scala:102)
[error] 	at leros.LerosTester$.delayedEndpoint$leros$LerosTester$1(LerosTester.scala:40)
[error] 	at leros.LerosTester$delayedInit$body.apply(LerosTester.scala:37)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at leros.LerosTester$.main(LerosTester.scala:37)
[error] 	at leros.LerosTester.main(LerosTester.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Caused by: java.io.FileNotFoundException: dd (No such file or directory)
[error] 	at java.io.FileInputStream.open0(Native Method)
[error] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[error] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[error] 	at scala.io.Source$.fromFile(Source.scala:91)
[error] 	at scala.io.Source$.fromFile(Source.scala:76)
[error] 	at scala.io.Source$.fromFile(Source.scala:54)
[error] 	at leros.util.Assembler$.assemble(Assembler.scala:47)
[error] 	at leros.util.Assembler$.assemble(Assembler.scala:41)
[error] 	at leros.util.Assembler$.getProgram(Assembler.scala:21)
[error] 	at leros.InstrMem.<init>(Leros.scala:40)
[error] 	at leros.Leros.$anonfun$mem$1(Leros.scala:79)
[error] 	at chisel3.Module$.do_apply(Module.scala:52)
[error] 	at leros.Leros.<init>(Leros.scala:79)
[error] 	at leros.LerosTester$.$anonfun$new$1(LerosTester.scala:39)
[error] 	at chisel3.Module$.do_apply(Module.scala:52)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.$anonfun$elaborate$1(ChiselAnnotations.scala:50)
[error] 	at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:414)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:412)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:50)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:19)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:352)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:18)
[error] 	at chisel3.iotesters.setupTreadleBackend$.apply(TreadleBackend.scala:143)
[error] 	at chisel3.iotesters.Driver$.$anonfun$execute$2(Driver.scala:53)
[error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[error] 	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:168)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at logger.Logger$.makeScope(Logger.scala:166)
[error] 	at logger.Logger$.makeScope(Logger.scala:127)
[error] 	at chisel3.iotesters.Driver$.$anonfun$execute$1(Driver.scala:38)
[error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
[error] 	at chisel3.iotesters.Driver$.execute(Driver.scala:38)
[error] 	at chisel3.iotesters.Driver$.execute(Driver.scala:102)
[error] 	at leros.LerosTester$.delayedEndpoint$leros$LerosTester$1(LerosTester.scala:40)
[error] 	at leros.LerosTester$delayedInit$body.apply(LerosTester.scala:37)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at leros.LerosTester$.main(LerosTester.scala:37)
[error] 	at leros.LerosTester.main(LerosTester.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Test / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Test / runMain) Nonzero exit code: 1
```

**Comment by schoeberl** [comment]
Run a plain

```make```

should work. Running all tests is a simple

```make all```

Just tried it on a fresh clone and it worked.
